

services:

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: unless-stopped
    init: true
    env_file: .env
    volumes:
      - database:/var/lib/mysql/
    networks:
      - inception
    
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: unless-stopped
    init: true
    env_file: .env
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - inception
    depends_on:
      - mariadb
    
  nginx:
    image: nginx
    container_name: nginx
    build: 
      context: ./requirements/nginx/
      args:
        CERT_FOLDER: ${CERT_FOLDER}
        CERTIFICATE: ${CERTIFICATE}
        KEY: ${KEY}

    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - inception
    restart: unless-stopped
    init: true
    env_file: .env
    depends_on:
      - wordpress



volumes:

  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/database

  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress


networks:
  inception:
    driver: bridge